"""initial tables

Revision ID: 19965fca45ad
Revises: 
Create Date: 2026-03-23 12:46:03.405966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19965fca45ad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('listings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lister_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('available_qty', sa.Integer(), nullable=False),
    sa.Column('daily_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_paused', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lister_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listings_category'), 'listings', ['category'], unique=False)
    op.create_index(op.f('ix_listings_lister_id'), 'listings', ['lister_id'], unique=False)
    op.create_table('rentals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('listing_id', sa.String(), nullable=False),
    sa.Column('borrower_id', sa.String(), nullable=False),
    sa.Column('lister_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('returned_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rejection_reason', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['borrower_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lister_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rentals_borrower_id'), 'rentals', ['borrower_id'], unique=False)
    op.create_index(op.f('ix_rentals_lister_id'), 'rentals', ['lister_id'], unique=False)
    op.create_index(op.f('ix_rentals_listing_id'), 'rentals', ['listing_id'], unique=False)
    op.create_table('damage_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rental_id', sa.String(), nullable=False),
    sa.Column('reported_by', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_damage_reports_rental_id'), 'damage_reports', ['rental_id'], unique=False)
    op.create_index(op.f('ix_damage_reports_reported_by'), 'damage_reports', ['reported_by'], unique=False)
    op.create_table('fines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rental_id', sa.String(), nullable=False),
    sa.Column('borrower_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('days_overdue', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['borrower_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fines_borrower_id'), 'fines', ['borrower_id'], unique=False)
    op.create_index(op.f('ix_fines_rental_id'), 'fines', ['rental_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rental_id', sa.String(), nullable=False),
    sa.Column('reviewer_id', sa.String(), nullable=False),
    sa.Column('reviewee_id', sa.String(), nullable=False),
    sa.Column('listing_id', sa.String(), nullable=True),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='rating_between_1_and_5'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_listing_id'), 'reviews', ['listing_id'], unique=False)
    op.create_index(op.f('ix_reviews_rental_id'), 'reviews', ['rental_id'], unique=False)
    op.create_index(op.f('ix_reviews_reviewee_id'), 'reviews', ['reviewee_id'], unique=False)
    op.create_index(op.f('ix_reviews_reviewer_id'), 'reviews', ['reviewer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_reviewer_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_reviewee_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_rental_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_listing_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_fines_rental_id'), table_name='fines')
    op.drop_index(op.f('ix_fines_borrower_id'), table_name='fines')
    op.drop_table('fines')
    op.drop_index(op.f('ix_damage_reports_reported_by'), table_name='damage_reports')
    op.drop_index(op.f('ix_damage_reports_rental_id'), table_name='damage_reports')
    op.drop_table('damage_reports')
    op.drop_index(op.f('ix_rentals_listing_id'), table_name='rentals')
    op.drop_index(op.f('ix_rentals_lister_id'), table_name='rentals')
    op.drop_index(op.f('ix_rentals_borrower_id'), table_name='rentals')
    op.drop_table('rentals')
    op.drop_index(op.f('ix_listings_lister_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_category'), table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###