"""add phone to listings

Revision ID: 2d9ac44ed184
Revises: 19965fca45ad
Create Date: 2026-03-30 07:37:06.369117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d9ac44ed184'
down_revision: Union[str, None] = '19965fca45ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'phone')
    # ### end Alembic commands ###