export const mockUser = {
  id: 'user-1',
  name: 'Hetal Savarde',
  email: 'hetal@example.com',
  phone: '9876543210',
  role: 'user' as const,
  created_at: '2026-01-01T10:00:00Z',
};

export const mockListings = [
  {
    id: 'lst-1',
    name: 'Cricket Bat - SG Striker',
    category: 'cricket',
    description: 'SG Striker bat, full size, excellent condition. Kashmir willow with premium grip. Perfect for weekend matches.',
    available_qty: 2,
    daily_rate: 50,
    location: 'Andheri, Mumbai',
    status: 'active' as const,
    avg_rating: 4.8,
    total_reviews: 12,
    created_at: '2026-01-15T10:00:00Z',
    lister: { id: 'user-2', name: 'Rutvika Vala', avg_rating: 4.8, phone: '9812345678' },
  },
  {
    id: 'lst-2',
    name: 'Football - Adidas Tango',
    category: 'football',
    description: 'Official size 5 match ball, FIFA quality certified. Great for turf and grass.',
    available_qty: 5,
    daily_rate: 30,
    location: 'Bandra, Mumbai',
    status: 'active' as const,
    avg_rating: 4.5,
    total_reviews: 8,
    created_at: '2026-02-01T10:00:00Z',
    lister: { id: 'user-3', name: 'Aditi Sharma', avg_rating: 4.6, phone: '9823456789' },
  },
  {
    id: 'lst-3',
    name: 'Badminton Racket - Yonex Astrox',
    category: 'badminton',
    description: 'Professional grade Yonex Astrox 88D. Strung at 26 lbs. Comes with cover.',
    available_qty: 1,
    daily_rate: 80,
    location: 'Koramangala, Bangalore',
    status: 'active' as const,
    avg_rating: 4.9,
    total_reviews: 15,
    created_at: '2026-01-20T10:00:00Z',
    lister: { id: 'user-4', name: 'Priya Nair', avg_rating: 4.9, phone: '9834567890' },
  },
  {
    id: 'lst-4',
    name: 'Tennis Racket - Wilson Pro Staff',
    category: 'tennis',
    description: 'Roger Federer edition. 97 sq in head, 315g. Freshly strung with Luxilon.',
    available_qty: 2,
    daily_rate: 120,
    location: 'Jubilee Hills, Hyderabad',
    status: 'active' as const,
    avg_rating: 4.3,
    total_reviews: 6,
    created_at: '2026-02-10T10:00:00Z',
    lister: { id: 'user-5', name: 'Rahul Mehta', avg_rating: 4.4, phone: '9845678901' },
  },
  {
    id: 'lst-5',
    name: 'Skateboard - Element Complete',
    category: 'skating',
    description: '8.0" deck with Independent trucks and Spitfire wheels. Good for street skating.',
    available_qty: 1,
    daily_rate: 60,
    location: 'Connaught Place, Delhi',
    status: 'active' as const,
    avg_rating: 4.1,
    total_reviews: 4,
    created_at: '2026-02-15T10:00:00Z',
    lister: { id: 'user-6', name: 'Vikram Singh', avg_rating: 4.2, phone: '9856789012' },
  },
  {
    id: 'lst-6',
    name: 'Cycling Helmet - Giro Aether',
    category: 'cycling',
    description: 'MIPS protection, size M. Lightweight with excellent ventilation. Like new condition.',
    available_qty: 3,
    daily_rate: 25,
    location: 'Viman Nagar, Pune',
    status: 'active' as const,
    avg_rating: 4.7,
    total_reviews: 9,
    created_at: '2026-03-01T10:00:00Z',
    lister: { id: 'user-2', name: 'Rutvika Vala', avg_rating: 4.8, phone: '9812345678' },
  },
];

export const mockBorrowerRentals = [
  {
    id: 'rent-1',
    listing_name: 'Cricket Bat - SG Striker',
    lister_name: 'Rutvika Vala',
    quantity: 1,
    start_date: '2026-03-20',
    due_date: '2026-03-25',
    status: 'active' as const,
    fine: null,
  },
  {
    id: 'rent-2',
    listing_name: 'Football - Adidas Tango',
    lister_name: 'Aditi Sharma',
    quantity: 2,
    start_date: '2026-03-10',
    due_date: '2026-03-15',
    status: 'returned' as const,
    fine: null,
  },
  {
    id: 'rent-3',
    listing_name: 'Badminton Racket - Yonex Astrox',
    lister_name: 'Priya Nair',
    quantity: 1,
    start_date: '2026-03-18',
    due_date: '2026-03-22',
    status: 'overdue' as const,
    fine: null,
  },
  {
    id: 'rent-4',
    listing_name: 'Tennis Racket - Wilson Pro Staff',
    lister_name: 'Rahul Mehta',
    quantity: 1,
    start_date: '2026-04-01',
    due_date: '2026-04-05',
    status: 'pending' as const,
    fine: null,
  },
  {
    id: 'rent-5',
    listing_name: 'Skateboard - Element Complete',
    lister_name: 'Vikram Singh',
    quantity: 1,
    start_date: '2026-02-01',
    due_date: '2026-02-05',
    status: 'cancelled' as const,
    fine: null,
  },
];

export const mockListerListings = [
  {
    id: 'my-lst-1',
    name: 'Yoga Mat - Manduka Pro',
    category: 'yoga',
    description: 'Premium 6mm thick mat. Non-slip surface.',
    available_qty: 4,
    daily_rate: 20,
    location: 'Andheri, Mumbai',
    status: 'active' as const,
    avg_rating: 4.6,
    total_reviews: 7,
    created_at: '2026-01-10T10:00:00Z',
    lister: { id: 'user-1', name: 'Hetal Savarde', avg_rating: 4.5, phone: '9876543210' },
  },
  {
    id: 'my-lst-2',
    name: 'Boxing Gloves - Everlast',
    category: 'boxing',
    description: '14oz training gloves. Well-padded.',
    available_qty: 2,
    daily_rate: 40,
    location: 'Andheri, Mumbai',
    status: 'paused' as const,
    avg_rating: 4.2,
    total_reviews: 3,
    created_at: '2026-02-20T10:00:00Z',
    lister: { id: 'user-1', name: 'Hetal Savarde', avg_rating: 4.5, phone: '9876543210' },
  },
];

export const mockListerRequests = [
  {
    id: 'lreq-1',
    listing_name: 'Yoga Mat - Manduka Pro',
    borrower_name: 'Aditi Sharma',
    borrower_phone: '9823456789',
    borrower_id: 'user-3',
    quantity: 1,
    start_date: '2026-04-01',
    due_date: '2026-04-05',
    status: 'pending' as const,
    fine_paid: false,
  },
  {
    id: 'lreq-2',
    listing_name: 'Yoga Mat - Manduka Pro',
    borrower_name: 'Vikram Singh',
    borrower_phone: '9834567890',
    borrower_id: 'user-6',
    quantity: 2,
    start_date: '2026-03-20',
    due_date: '2026-03-28',
    status: 'active' as const,
    fine_paid: false,
  },
  {
    id: 'lreq-3',
    listing_name: 'Boxing Gloves - Everlast',
    borrower_name: 'Rahul Mehta',
    borrower_phone: '9845678901',
    borrower_id: 'user-5',
    quantity: 1,
    start_date: '2026-03-01',
    due_date: '2026-03-05',
    status: 'returned' as const,
    fine_paid: true,
  },
];

export const mockFines = [
  {
    id: 'fine-1',
    rental_id: 'rent-old-1',
    listing_name: 'Cricket Bat - SG Striker',
    borrower_name: 'Aditi Sharma',
    borrower_id: 'user-3',
    lister_id: 'user-1',
    amount: 100,
    days_overdue: 2,
    status: 'unpaid' as const,
    created_at: '2026-03-07T00:00:00Z',
  },
  {
    id: 'fine-2',
    rental_id: 'rent-old-2',
    listing_name: 'Yoga Mat - Manduka Pro',
    borrower_name: 'Vikram Singh',
    borrower_id: 'user-6',
    lister_id: 'user-1',
    amount: 200,
    days_overdue: 4,
    status: 'unpaid' as const,
    created_at: '2026-03-10T00:00:00Z',
  },
];

export const mockReviews = [
  {
    id: 'rev-1',
    reviewer: { id: 'user-3', name: 'Aditi Sharma' },
    rating: 5,
    comment: 'Bat was in great condition, highly recommend!',
    created_at: '2026-03-16T10:00:00Z',
  },
  {
    id: 'rev-2',
    reviewer: { id: 'user-6', name: 'Vikram Singh' },
    rating: 4,
    comment: 'Good quality, but grip was slightly worn.',
    created_at: '2026-03-10T10:00:00Z',
  },
  {
    id: 'rev-3',
    reviewer: { id: 'user-4', name: 'Priya Nair' },
    rating: 5,
    comment: 'Perfect for my weekend match. Will rent again!',
    created_at: '2026-03-05T10:00:00Z',
  },
];

// Category icons/emojis for listing cards
export const categoryIcons: Record<string, string> = {
  cricket: '🏏',
  football: '⚽',
  badminton: '🏸',
  tennis: '🎾',
  skating: '🛹',
  cycling: '🚴',
  yoga: '🧘',
  boxing: '🥊',
  swimming: '🏊',
  basketball: '🏀',
};

export const categories = [
  'cricket', 'football', 'badminton', 'tennis', 'skating',
  'cycling', 'yoga', 'boxing', 'swimming', 'basketball',
];
